set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*:Tc"

set -g extended-keys on
set -ga terminal-features 'xterm*:extkeys'
set -s extended-keys-format csi-u

set -g xterm-keys on

set -g escape-time 10
set -g focus-events on
set -g mouse on
set -g history-limit 50000
